name: zebra_scanner
description: Flutter project structure for Zebra scanner application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0-dev

include: package:flutter_lints/flutter.yaml

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter_modular: ^4.3.0
  flutter_triple: ^1.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fast_i18n: ^5.9.0
  dio: ^4.0.4
  my_logger: ^1.0.0
  cupertino_icons: ^1.0.3

  equatable: ^2.0.3
  copy_with_extension: ^4.0.0
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0
  shared_preferences: ^2.0.11
  sentry_flutter: ^6.2.2
  sentry_dio: ^6.2.2

  flutter_platform_widgets: ^1.12.1
  back_button_interceptor: ^5.0.2
  flutterlifecyclehooks: ^2.0.0
  flutter_secure_storage: ^5.0.2

  prompt_dialog: ^1.0.9
  shirne_dialog: ^1.6.0
  another_flushbar: ^1.10.28
  flutter_typeahead: ^3.2.1

  qr_flutter: ^4.0.0
  flutter_beep: ^1.0.0
  flutter_signature_pad: ^3.0.0
  flutter_barcode_scanner: ^2.0.0

  image: ^3.1.1
  tuple: ^2.0.0
  crypto: ^3.0.1
  sprintf: ^6.0.0
  html_unescape: ^2.0.0

  platform_device_id: ^1.0.1
  package_info_plus: ^1.3.0
  network_info_plus: ^2.1.2
  connectivity_plus: ^2.2.0

dev_dependencies:
  modular_test: ^1.0.1+1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  build_runner: any
  flutter_lints: ^1.0.4
  copy_with_extension_gen: ^4.0.0
  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1

flutter_app_name:
  name: Zebra Scanner

flutter_icons:
  image_path: assets/icon.png
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icon_foreground.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_screen.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
